#!/usr/bin/env php
<?php

/*
 * --------------------------------------------------------------------
 * CodeIgniter 4 command line tool
 * --------------------------------------------------------------------
 *
 * This tool allows you to run the framework from the command line
 * to execute tasks and perform maintenance.
 */

// Check if the current directory is the project root
if (! is_file(__DIR__ . '/public/index.php')) {
    fwrite(STDERR, "You must run this command from the project root.\n\n");
    exit(1);
}

// Refuse to run when called from php-cgi
if (strpos(PHP_SAPI, 'cgi') === 0) {
    exit("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// Path to the front controller (this file)
define('FCPATH', __DIR__ . '/public' . DIRECTORY_SEPARATOR);

/*
 * --------------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 * --------------------------------------------------------------------
 * This process sets up the path constants, loads and registers
 * our autoloader, along with Composer's, loads our constants
 * and fires up an environment-specific bootstrapping.
 */

// Load our paths config file
// This is the line that might need adjustment based on where this file is located.
require __DIR__ . '/app/Config/Paths.php';

$paths = new Config\Paths();

// Location of the framework bootstrap file.
require rtrim($paths->systemDirectory, '\\/ ') . DIRECTORY_SEPARATOR . 'Boot.php';

exit(CodeIgniter\Boot::bootSpark($paths));
